// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface CalculatorManagerPrx extends Ice.ObjectPrx
{
    public CalculatorPrx giveMeOneCalculatorReference();

    public CalculatorPrx giveMeOneCalculatorReference(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference();

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(Ice.Callback __cb);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(Callback_CalculatorManager_giveMeOneCalculatorReference __cb);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(java.util.Map<String, String> __ctx, Callback_CalculatorManager_giveMeOneCalculatorReference __cb);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(IceInternal.Functional_GenericCallback1<CalculatorPrx> __responseCb, 
                                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(IceInternal.Functional_GenericCallback1<CalculatorPrx> __responseCb, 
                                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(java.util.Map<String, String> __ctx, 
                                                              IceInternal.Functional_GenericCallback1<CalculatorPrx> __responseCb, 
                                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_giveMeOneCalculatorReference(java.util.Map<String, String> __ctx, 
                                                              IceInternal.Functional_GenericCallback1<CalculatorPrx> __responseCb, 
                                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                              IceInternal.Functional_BoolCallback __sentCb);

    public CalculatorPrx end_giveMeOneCalculatorReference(Ice.AsyncResult __result);
}
