// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `WalkieTalkieEar.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package walkieTalkie;

public interface Ear extends Ice.Object,
                             _EarOperations, _EarOperationsNC
{
    public static final String ice_staticId = "::walkieTalkie::Ear";

    public static final long serialVersionUID = 7995201754306387752L;
}
