// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `WalkieTalkieEar.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package walkieTalkie;

public final class EarPrxHolder
{
    public
    EarPrxHolder()
    {
    }

    public
    EarPrxHolder(EarPrx value)
    {
        this.value = value;
    }

    public EarPrx value;
}
