// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public final class CalculatorManagerPrxHelper extends Ice.ObjectPrxHelperBase implements CalculatorManagerPrx
{
    private static final String __giveMeTheCalculators_name = "giveMeTheCalculators";

    public void giveMeTheCalculators(CalculatorVectorHolder calcVector)
    {
        giveMeTheCalculators(calcVector, null, false);
    }

    public void giveMeTheCalculators(CalculatorVectorHolder calcVector, java.util.Map<String, String> __ctx)
    {
        giveMeTheCalculators(calcVector, __ctx, true);
    }

    private void giveMeTheCalculators(CalculatorVectorHolder calcVector, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__giveMeTheCalculators_name);
        end_giveMeTheCalculators(calcVector, begin_giveMeTheCalculators(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_giveMeTheCalculators()
    {
        return begin_giveMeTheCalculators(null, false, false, null);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(java.util.Map<String, String> __ctx)
    {
        return begin_giveMeTheCalculators(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(Ice.Callback __cb)
    {
        return begin_giveMeTheCalculators(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_giveMeTheCalculators(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(Callback_CalculatorManager_giveMeTheCalculators __cb)
    {
        return begin_giveMeTheCalculators(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(java.util.Map<String, String> __ctx, Callback_CalculatorManager_giveMeTheCalculators __cb)
    {
        return begin_giveMeTheCalculators(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(IceInternal.Functional_GenericCallback1<CalculatorPrx[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_giveMeTheCalculators(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(IceInternal.Functional_GenericCallback1<CalculatorPrx[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_giveMeTheCalculators(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<CalculatorPrx[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_giveMeTheCalculators(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_giveMeTheCalculators(java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<CalculatorPrx[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_giveMeTheCalculators(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_giveMeTheCalculators(java.util.Map<String, String> __ctx, 
                                                       boolean __explicitCtx, 
                                                       boolean __synchronous, 
                                                       IceInternal.Functional_GenericCallback1<CalculatorPrx[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_giveMeTheCalculators(__ctx, __explicitCtx, __synchronous, 
                                          new IceInternal.Functional_TwowayCallbackArg1<utils.CalculatorPrx[]>(__responseCb, __exceptionCb, __sentCb)
                                              {
                                                  public final void __completed(Ice.AsyncResult __result)
                                                  {
                                                      CalculatorManagerPrxHelper.__giveMeTheCalculators_completed(this, __result);
                                                  }
                                              });
    }

    private Ice.AsyncResult begin_giveMeTheCalculators(java.util.Map<String, String> __ctx, 
                                                       boolean __explicitCtx, 
                                                       boolean __synchronous, 
                                                       IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__giveMeTheCalculators_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__giveMeTheCalculators_name, __cb);
        try
        {
            __result.prepare(__giveMeTheCalculators_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_giveMeTheCalculators(CalculatorVectorHolder calcVector, Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __giveMeTheCalculators_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            calcVector.value = CalculatorVectorHelper.read(__is);
            __result.endReadParams();
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __giveMeTheCalculators_completed(Ice.TwowayCallbackArg1<CalculatorPrx[]> __cb, Ice.AsyncResult __result)
    {
        utils.CalculatorManagerPrx __proxy = (utils.CalculatorManagerPrx)__result.getProxy();
        CalculatorVectorHolder calcVector = new CalculatorVectorHolder();
        try
        {
            __proxy.end_giveMeTheCalculators(calcVector, __result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(calcVector.value);
    }

    public static CalculatorManagerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), CalculatorManagerPrx.class, CalculatorManagerPrxHelper.class);
    }

    public static CalculatorManagerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), CalculatorManagerPrx.class, CalculatorManagerPrxHelper.class);
    }

    public static CalculatorManagerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), CalculatorManagerPrx.class, CalculatorManagerPrxHelper.class);
    }

    public static CalculatorManagerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), CalculatorManagerPrx.class, CalculatorManagerPrxHelper.class);
    }

    public static CalculatorManagerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, CalculatorManagerPrx.class, CalculatorManagerPrxHelper.class);
    }

    public static CalculatorManagerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, CalculatorManagerPrx.class, CalculatorManagerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::utils::CalculatorManager"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, CalculatorManagerPrx v)
    {
        __os.writeProxy(v);
    }

    public static CalculatorManagerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            CalculatorManagerPrxHelper result = new CalculatorManagerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
