// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public final class CalculatorVectorHelper
{
    public static void
    write(IceInternal.BasicStream __os, CalculatorPrx[] __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                CalculatorPrxHelper.__write(__os, __v[__i0]);
            }
        }
    }

    public static CalculatorPrx[]
    read(IceInternal.BasicStream __is)
    {
        CalculatorPrx[] __v;
        final int __len0 = __is.readAndCheckSeqSize(2);
        __v = new CalculatorPrx[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = CalculatorPrxHelper.__read(__is);
        }
        return __v;
    }
}
