// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface Listener extends Ice.Object,
                                  _ListenerOperations, _ListenerOperationsNC
{
    public static final String ice_staticId = "::chat::Listener";

    public static final long serialVersionUID = -6877136600900370947L;
}
