// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ListenerPrx extends Ice.ObjectPrx
{
    public void messageNotification(int numMessage);

    public void messageNotification(int numMessage, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_messageNotification(int numMessage);

    public Ice.AsyncResult begin_messageNotification(int numMessage, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_messageNotification(int numMessage, Ice.Callback __cb);

    public Ice.AsyncResult begin_messageNotification(int numMessage, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_messageNotification(int numMessage, Callback_Listener_messageNotification __cb);

    public Ice.AsyncResult begin_messageNotification(int numMessage, java.util.Map<String, String> __ctx, Callback_Listener_messageNotification __cb);

    public Ice.AsyncResult begin_messageNotification(int numMessage, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_messageNotification(int numMessage, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_messageNotification(int numMessage, 
                                                     java.util.Map<String, String> __ctx, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_messageNotification(int numMessage, 
                                                     java.util.Map<String, String> __ctx, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb);

    public void end_messageNotification(Ice.AsyncResult __result);
}
