// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Listener.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package forum;

public interface ListenerPrx extends Ice.ObjectPrx
{
    public void newPublication(String str);

    public void newPublication(String str, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_newPublication(String str);

    public Ice.AsyncResult begin_newPublication(String str, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_newPublication(String str, Ice.Callback __cb);

    public Ice.AsyncResult begin_newPublication(String str, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_newPublication(String str, Callback_Listener_newPublication __cb);

    public Ice.AsyncResult begin_newPublication(String str, java.util.Map<String, String> __ctx, Callback_Listener_newPublication __cb);

    public Ice.AsyncResult begin_newPublication(String str, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_newPublication(String str, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_newPublication(String str, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_newPublication(String str, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public void end_newPublication(Ice.AsyncResult __result);
}
