// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface ClockPrx extends Ice.ObjectPrx
{
    public void publish(String data);

    public void publish(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_publish(String data);

    public Ice.AsyncResult begin_publish(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_publish(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_publish(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_publish(String data, Callback_Clock_publish __cb);

    public Ice.AsyncResult begin_publish(String data, java.util.Map<String, String> __ctx, Callback_Clock_publish __cb);

    public Ice.AsyncResult begin_publish(String data, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_publish(String data, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_publish(String data, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_publish(String data, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_publish(Ice.AsyncResult __result);
}
