// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `VectorManipulator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface _VectorManipulatorOperations
{
    void sort(int[] inVector, IntVectorHolder outVector, Ice.Current __current);

    void copyWithoutDuplicates(int[] inVector, IntVectorHolder outVector, Ice.Current __current);
}
