// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface Calculator extends Ice.Object,
                                    _CalculatorOperations, _CalculatorOperationsNC
{
    public static final String ice_staticId = "::utils::Calculator";

    public static final long serialVersionUID = 2849867149415732598L;
}
