// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface CalculatorPrx extends Ice.ObjectPrx
{
    public int numOps();

    public int numOps(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_numOps();

    public Ice.AsyncResult begin_numOps(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_numOps(Ice.Callback __cb);

    public Ice.AsyncResult begin_numOps(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_numOps(Callback_Calculator_numOps __cb);

    public Ice.AsyncResult begin_numOps(java.util.Map<String, String> __ctx, Callback_Calculator_numOps __cb);

    public Ice.AsyncResult begin_numOps(IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_numOps(IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_numOps(java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_numOps(java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public int end_numOps(Ice.AsyncResult __result);

    public int gcd(int a, int b);

    public int gcd(int a, int b, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(int a, int b);

    public Ice.AsyncResult begin_gcd(int a, int b, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(int a, int b, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(int a, int b, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(int a, int b, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(int a, int b, java.util.Map<String, String> __ctx, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(int a, 
                                     int b, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(int a, 
                                     int b, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_gcd(int a, 
                                     int b, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(int a, 
                                     int b, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public int end_gcd(Ice.AsyncResult __result);

    public int factorial(int n);

    public int factorial(int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_factorial(int n);

    public Ice.AsyncResult begin_factorial(int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_factorial(int n, Ice.Callback __cb);

    public Ice.AsyncResult begin_factorial(int n, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_factorial(int n, Callback_Calculator_factorial __cb);

    public Ice.AsyncResult begin_factorial(int n, java.util.Map<String, String> __ctx, Callback_Calculator_factorial __cb);

    public Ice.AsyncResult begin_factorial(int n, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_factorial(int n, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_factorial(int n, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_factorial(int n, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public int end_factorial(Ice.AsyncResult __result);
}
